Repairs/ViewModels/CategoryViewModel.cs
namespace Repairs.ViewModels
{
    public class CategoryViewModel
    {

    }
}

Repairs/ViewModels/ExtraQuestionsViewModel.cs
namespace Repairs.ViewModels
{
    public class ExtraQuestionsViewModel
    {
        public string TaskCategory { get; set; }

        public string TaskSubCategory { get; set; }

        public string Task { get; set; }

        public string TaskCode { get; set; }

        public string Question1 { get; set; }

        public string Question2 { get; set; }

        public string Question3 { get; set; }

        public string Answer1 { get; set; }

        public string Answer2 { get; set; }

        public string Answer3 { get; set; }

        public double Latitude { get; set; }

        public double Longitude { get; set; }
    }
}

Repairs/ViewModels/SubCategoryViewModel.cs
namespace Repairs.ViewModels
{
    using System.Collections.Generic;

    using Repairs.Models.Tasks;

    public class SubCategoryViewModel
    {
        public IList<TaskSubCategory> SubCategories { get; set; }

        public string TaskCategory { get; set; }
    }
}

Repairs/ViewModels/TaskViewModel.cs
using Repairs.Models.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Repairs.ViewModels
{
    public class TaskViewModel
    {
        public IList<Task> Tasks { get; set; }

        public string TaskCategory { get; set; }

        public string TaskSubCategory { get; set; }
    }
}

Repairs/Controllers/DiagnoseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repairs.Controllers
{
    using Moat.Api.Helpers;
    using Repairs.Models.Tasks;
    using Repairs.Service;
    using Repairs.ViewModels;

    public class DiagnoseController : Controller
    {
        public ActionResult Index()
        {
            return this.View(new CategoryViewModel()
            {
                Categories = this.GetTasks()
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Index(TaskCategory category)
        {
            var subCategories = this.GetTasks()
                .First(x => x.Title == category.Title)
                .SubCategories;

            return PartialView("SubCategoryStep", new SubCategoryViewModel()
            {
                SubCategories = subCategories,
                TaskCategory = category.Title
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult SubCategoryStep(
            TaskSubCategory taskSubCategory,
            string taskCategory)
        {
            var subCategories = this.GetTasks()
                .First(x => x.Title == taskCategory)
                .SubCategories;

            var tasks = subCategories
                .First(x => x.Title == taskSubCategory.Title)
                .Tasks;

            return PartialView("TaskStep", new TaskViewModel()
            {
                Tasks = tasks,
                TaskCategory = taskCategory,
                TaskSubCategory = taskSubCategory.Title
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult TaskStep(
            Task task,
            string taskSubCategory,
            string taskCategory)
        {
            var subCategories = this.GetTasks()
                .First(x => x.Title == taskCategory)
                .SubCategories;

            var tasks = subCategories
                .First(x => x.Title == taskSubCategory)
                .Tasks;

            var selectedTask = tasks
                .First(x => x.TaskDescription == task.TaskDescription);

            return PartialView("ExtraQuestionsStep", new ExtraQuestionsViewModel()
            {
                TaskCategory = taskCategory,
                TaskSubCategory = taskSubCategory,
                Task = selectedTask.TaskDescription,
                TaskCode = selectedTask.TaskCode,
                Question1 = "Please give details on the location (e.g. which floor, which door, room)",
                Question2 = "Extra question 2 that is specific to the task in question",
                Question3 = "Extra question 3 asked to get more detail"
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult ExtraQuestionsStep(ExtraQuestionsViewModel vm, HttpPostedFileBase file)
        {
            if (file != null)
            {
                IGeolocationService geo = new GeolocationService();
                var location = geo.GetLocation(file.InputStream);
                vm.Latitude = location.Latitude;
                vm.Longitude = location.Longitude;
            }

            return View("Summary", vm);
        }

        private IList<TaskCategory> GetTasks()
        {
            var repairTasksRepository = new RepairTaskRepository();
            var jsonTasksService = new JsonTasksService(repairTasksRepository);
            return jsonTasksService.GetTaskCategoriesFiltered(
                DirectoryHelper.MapPath("~/App_Data/jsonData.json"),
                "P");
        }
    }
}

Repairs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repairs.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Repairs/Views/Diagnose/ExtraQuestionsStep.cshtml
@using Repairs.Models
@model Repairs.ViewModels.ExtraQuestionsViewModel
<hr />

<div class="columns">

    <div class="column is-6">

        @using (Html.BeginForm("ExtraQuestionsStep", "Diagnose", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => Model.TaskCategory)
            @Html.HiddenFor(x => Model.TaskSubCategory)
            @Html.HiddenFor(x => Model.Task)
            @Html.HiddenFor(x => Model.TaskCode)
            @Html.HiddenFor(x => Model.Question1)
            @Html.HiddenFor(x => Model.Question2)
            @Html.HiddenFor(x => Model.Question3)
            <div class="field">
                <label class="label">@Model.Question1</label>
                <p class="control">
                    @Html.TextAreaFor(x => x.Answer1, new { @class = "textarea", placeholder = "Maximum 500 words" })
                </p>
            </div>

            <div class="field">
                <label class="label">@Model.Question2</label>
                <p class="control">
                    @Html.TextAreaFor(x => x.Answer2, new { @class = "textarea", placeholder = "Maximum 500 words" })
                </p>
            </div>

            <div class="field">
                <label class="label">@Model.Question3</label>
                <p class="control">
                    @Html.TextAreaFor(x => x.Answer3, new { @class = "textarea", placeholder = "Maximum 500 words" })
                </p>
            </div>
                       
            <div class="field">
                <label class="label">Please upload a photo of the problem area</label>
               
                <div class="file">
                    <label class="file-label">
                        <input class="file-input" type="file" name="file" id="file">
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Choose a file…
                            </span>
                        </span>
                        <span class="file-name" id="filename">
                        </span>
                    </label>
                </div>
            </div>

            <a class="button is-rounded" href="javascript:$('form').submit();">Submit</a>
        }
    </div>

</div>

Repairs/Views/Diagnose/Index.cshtml
@using Repairs.Models
@model Repairs.ViewModels.CategoryViewModel
@{
    ViewBag.Title = "Log a repair";
}

<div class="columns">
    <div class="column is-12">

        <section class="section">
            <h1 class="title">Report a repair</h1>
            <p class="subtitle">What is your issue regarding?</p>
        </section>


        <div class="card is-shady">
            <div class="card-content">

                <div id="CategoryStep" class="step">
                    <div class="columns">
                        
                        <div class="column is-6">
                            @using (Ajax.BeginForm("Index", "Diagnose", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "SubCategoryStep", OnSuccess = "highlightSelectedFormElement('CategoryStep', data, 'SubCategoryStepForm')" }, new { @id = "CategoryStepForm", @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">

                                    @foreach (var category in Model.Categories)
                                    {
                                        <div>
                                            <label>
                                                <a class="button is-fullwidth tag__custom"> @category.Title </a>
                                                @Html.RadioButtonFor(m => category.Title, category.Title)
                                            </label>
                                        </div>
                                    }

                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div id="SubCategoryStep" class="step"></div>

                <div id="TaskStep" class="step"></div>

                <div id="ExtraQuestionsStep"></div>
            </div>
        </div>
    </div>
</div>

Repairs/Views/Diagnose/SubCategoryStep.cshtml
@using Repairs.Models
@model Repairs.ViewModels.SubCategoryViewModel
<hr />

<div class="columns">
    
    <div class="column is-6">
        @using (Ajax.BeginForm("SubCategoryStep", "Diagnose", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "TaskStep", OnSuccess = "highlightSelectedFormElement('SubCategoryStep', data, 'TaskStepForm')" }, new { @id = "SubCategoryStepForm", @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.HiddenFor(x => Model.TaskCategory)
                @foreach (var taskSubCategory in Model.SubCategories)
                {
                    <div>
                        <label>
                            <a class="button is-fullwidth tag__custom"> @taskSubCategory.Title </a>
                            @Html.RadioButtonFor(m => taskSubCategory.Title, taskSubCategory.Title)
                        </label>
                    </div>
                }
            </div>
        }
    </div>

</div>

Repairs/Views/Diagnose/Summary.cshtml
@using Repairs.Models
@model Repairs.ViewModels.ExtraQuestionsViewModel

<div class="columns">
    <div class="column is-12">

        <section class="section">
            <h1 class="title">Report a repair</h1>
            <p class="subtitle">A summary of your repair report.</p>
        </section>

        <div class="card is-shady">
            <header class="card-header">
                <p class="card-header-title"> Here are the details you have submitted </p>
                <a class="card-header-icon">
                    <span class="icon"> <i class="fa fa-angle-down"></i> </span>
                </a>
            </header>
            <div class="card-content">

                <div class="content">

                    <div class="columns">

                        <div class="column is-6">


                            <div class="field">
                                <label class="label">Task Category</label>
                                <p class="control">
                                    @Model.TaskCategory
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">Task Sub Category</label>
                                <p class="control">
                                    @Model.TaskSubCategory
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">Task</label>
                                <p class="control">
                                    @Model.Task
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">Task Code</label>
                                <p class="control">
                                    @Model.TaskCode
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">@Model.Question1</label>
                                <p class="control">
                                    @Model.Answer1
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">@Model.Question2</label>
                                <p class="control">
                                    @Model.Answer2
                                </p>
                            </div>

                            <div class="field">
                                <label class="label">@Model.Question3</label>
                                <p class="control">
                                    @Model.Answer3
                                </p>
                            </div>
                        </div>
                        
                        @if (Model.Latitude != 0)
                        {
                            <div class="column is-6">

                                <iframe frameborder="0"
                                        scrolling="no"
                                        marginheight="0"
                                        marginwidth="0"
                                        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBa_8jC62c8MZze9ngVNmwZCUna0NiKLv4&q=@Model.Latitude,@Model.Longitude&zoom=13"></iframe>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Repairs/Views/Diagnose/TaskStep.cshtml
@using Repairs.Models
@model Repairs.ViewModels.TaskViewModel
<hr />

<div class="columns">
    
    <div class="column is-6">
        @using (Ajax.BeginForm("TaskStep", "Diagnose", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "ExtraQuestionsStep", OnSuccess = "highlightSelectedFormElement('TaskStep', data)" }, new { @id = "TaskStepForm", @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.HiddenFor(x => Model.TaskCategory)
            @Html.HiddenFor(x => Model.TaskSubCategory)
            @foreach (var task in Model.Tasks)
            {
                <div>
                    <label>
                        <a class="button is-fullwidth tag__custom"> @task.TaskDescription </a>
                        @Html.RadioButtonFor(m => task.TaskDescription, task.TaskDescription)
                    </label>
                </div>
            }
        </div>
        }
    </div>
</div>

Repairs/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Repairs/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Repairs/Views/Home/Index.cshtml
<section class="hero is-medium is-dark is-bold">
    <div class="hero-body">
        <div class="container has-text-centered">
            <p class="hero__logo">
                <i class="fas fa-tools fa-5x"></i>
            </p>
           
            <p class="title">
                Diagnose Repairs
            </p>
            <p class="subtitle">
                PITCH
            </p>
            <p class="subtitle">
                <a class="button is-outlined" href="@Url.Action("Index","Diagnose")"> Log a repair </a>
            </p>
        </div>
    </div>
</section>

Repairs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PITCH</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://kit.fontawesome.com/6afd7c7fb7.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar is-link">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <i class="fas fa-tools fa-3x"></i>
            </a>
            <div class="navbar-burger burger" data-target="navMenuExample3">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuExample3" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item " href="/">
                    <h1>Diagnose Repairs</h1>
                </a>
            </div>
            <div class="navbar-end">
              
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

        @*<footer class="footer">
            <div class="container">
                <div class="columns">
                    <div class="column is-3 is-offset-2">
                        <h2>
                            <strong>Category</strong>
                        </h2>
                        <ul>
                            <li>
                                <a href="#">Lorem ipsum dolor sit amet</a>
                            </li>
                            <li>
                                <a href="#">Vestibulum errato isse</a>
                            </li>
                            <li>
                                <a href="#">Lorem ipsum dolor sit amet</a>
                            </li>
                            <li>
                                <a href="#">Aisia caisia</a>
                            </li>
                            <li>
                                <a href="#">Murphy's law</a>
                            </li>
                            <li>
                                <a href="#">Flimsy Lavenrock</a>
                            </li>
                            <li>
                                <a href="#">Maven Mousie Lavender</a>
                            </li>
                        </ul>
                    </div>
                    <div class="column is-3">
                        <h2>
                            <strong>Category</strong>
                        </h2>
                        <ul>
                            <li>
                                <a href="#">Labore et dolore magna aliqua</a>
                            </li>
                            <li>
                                <a href="#">Kanban airis sum eschelor</a>
                            </li>
                            <li>
                                <a href="#">Modular modern free</a>
                            </li>
                            <li>
                                <a href="#">The king of clubs</a>
                            </li>
                            <li>
                                <a href="#">The Discovery Dissipation</a>
                            </li>
                            <li>
                                <a href="#">Course Correction</a>
                            </li>
                            <li>
                                <a href="#">Better Angels</a>
                            </li>
                        </ul>
                    </div>
                    <div class="column is-4">
                        <h2>
                            <strong>Category</strong>
                        </h2>
                        <ul>
                            <li>
                                <a href="#">Objects in space</a>
                            </li>
                            <li>
                                <a href="#">Playing cards with coyote</a>
                            </li>
                            <li>
                                <a href="#">Goodbye Yellow Brick Road</a>
                            </li>
                            <li>
                                <a href="#">The Garden of Forking Paths</a>
                            </li>
                            <li>
                                <a href="#">Future Shock</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>*@
    </div>


@*Scripts*@
@Scripts.Render("~/bundles/jquery") 
@Scripts.Render("~/bundles/jqueryval") 
<!-- Custom Form -->
@Scripts.Render("~/scripts/custom-form") 
@RenderSection("scripts", required: false) 
</body>
</html>